name: blog frontend CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: yarn install --frozen-lockfile # the yarn.lock is updated according to the node version
    - name: Lint Code
      run: yarn eslint
    - name: Run tests
      run: yarn test:fix
